version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"  # Пробрасываем порт 8000
    volumes:
      - ./app:/app  # Монтируем локальную папку app в папку внутри контейнера
    restart: always  # Контейнер перезапустится при сбое
